# Generated by Django 4.2.17 on 2024-12-11 12:31

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosSociais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificados', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('facebook', models.CharField(max_length=200, verbose_name='Facebook')),
                ('instagram', models.CharField(max_length=200, verbose_name='Instagram')),
                ('emails', models.CharField(max_length=200, verbose_name='Emails')),
                ('outras_redes', models.CharField(max_length=200, verbose_name='Outras Redes')),
                ('dados_enjoyers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_sociais', to='core.enjoyer')),
            ],
            options={
                'verbose_name': 'Dado Social',
                'verbose_name_plural': 'Dados Sociais',
            },
        ),
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificados', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=60, verbose_name='Sexo')),
                ('CPF', models.CharField(max_length=200, verbose_name='CPF')),
                ('estado_civil', models.CharField(max_length=100, verbose_name='Estado Civil')),
                ('telefones', models.CharField(max_length=100, verbose_name='Número de Telefone')),
                ('foto_pessoal', stdimage.models.StdImageField(force_min_size=False, upload_to='foto_pessoal/', variations={'medium': (300, 300), 'thumbnail': (100, 100)})),
                ('dados_enjoyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_pessoais', to='core.enjoyer')),
            ],
            options={
                'verbose_name': 'Dado Pessoal',
                'verbose_name_plural': 'Dados Pessoais',
            },
        ),
        migrations.CreateModel(
            name='DadosPatrimoniais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificados', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('moradia', models.TextField(verbose_name='Moradia(s)')),
                ('veiculos', models.TextField(verbose_name='Veículo(s)')),
                ('empresas', models.TextField(verbose_name='Empresa(s)')),
                ('cnpj', models.IntegerField(verbose_name='CNPJ')),
                ('dados_enjoyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_patrimoniais', to='core.enjoyer')),
            ],
            options={
                'verbose_name': 'Dado Patrimonial',
                'verbose_name_plural': 'Dados Pratrimoniais',
            },
        ),
    ]
