# Generated by Django 4.2.17 on 2024-12-11 12:31

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificacaoPMPB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificados', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('curso_realizados', models.CharField(max_length=200, verbose_name='Cursos de Qualificação')),
                ('data_conclusao', models.DateField(verbose_name='Data de Conclusão')),
                ('dados_enjoyers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualificacao_pmpb', to='core.enjoyer')),
            ],
            options={
                'verbose_name': 'Qualificação PMPB',
                'verbose_name_plural': 'Qualificações PMPB',
            },
        ),
        migrations.CreateModel(
            name='QualificacaoPessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificados', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('post_grad', models.CharField(max_length=200, verbose_name='Post/Grad')),
                ('instituicao', models.CharField(max_length=200, verbose_name='Instutuição')),
                ('numero_matricula', models.IntegerField(verbose_name='Número da Matrícula')),
                ('numero_admissao', models.IntegerField(verbose_name='Número de Admissão')),
                ('enderecos', models.TextField(verbose_name='Endereços')),
                ('nome_cpf_pai', models.CharField(max_length=255, verbose_name='Nome e CPF do pai')),
                ('nome_cpf_mae', models.CharField(max_length=255, verbose_name='Nome e CPF da Mãe')),
                ('nome_cpf_irmaos', models.CharField(max_length=255, verbose_name='Nome e CPF dos Irmãos')),
                ('nome_cpf_conjugue', models.CharField(max_length=255, verbose_name='Nome e CPF do conjugue')),
                ('nome_cpf_filhos', models.CharField(max_length=255, verbose_name='Nome e CPF dos filhos')),
                ('dados_enjoyers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualificacao_pessoal', to='core.enjoyer')),
            ],
            options={
                'verbose_name': 'Qualificação Pessoal',
                'verbose_name_plural': 'Qualificações Pessoais',
            },
        ),
        migrations.CreateModel(
            name='QualificacaoExtraPMPB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificados', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nivel_escolaridade', models.CharField(max_length=200, verbose_name='Nível de Escolaridade')),
                ('curso', models.CharField(max_length=200, verbose_name='Curso')),
                ('declaracao_matricula', stdimage.models.StdImageField(force_min_size=False, upload_to='declaracao_matricula/', variations={'medium': (300, 300), 'thumbnail': (100, 100)})),
                ('dados_enjoyers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualificacao_extra_pmpb', to='core.enjoyer')),
            ],
            options={
                'verbose_name': 'Qualificação Extra PMPB',
                'verbose_name_plural': 'Qualificações Extras da PMPB',
            },
        ),
        migrations.CreateModel(
            name='QualificacaoAreaInteligencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificados', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('curso_inteligencia', models.CharField(max_length=255, verbose_name='Curso Inteligencia')),
                ('data_conclusao', models.DateField(verbose_name='Data de Conclusão')),
                ('dados_enjoyers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualificacao_area_inteligencia', to='core.enjoyer')),
            ],
            options={
                'verbose_name': 'Qualificação na Área Inteligência',
                'verbose_name_plural': 'Qualificações na Área de Inteligência',
            },
        ),
    ]
